name: Bug Report
description: File a bug report
title: "[Contributor Form]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: name
    attributes:
      label: Author name (including pronouns if desired)
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: Traditional country
      description: e.g, Whadjuk boodja
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact link 
      description: e.g, email, Twitter, LinkedIn, etc
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Content
    validations:
      required: true
  - type: dropdown
    id: level
    attributes:
      label: Content level
      options:
        - Novice
        - Intermediate
        - Advanced
    validations:
      required: true
  - type: textarea
    id: contentsummary
    attributes:
      label: Content summary
      description: Please provide 2-3 sentences
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Please provide a couple of keywords to describe your content.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
